### ISSUE TITLE
运行环境

### ISSUE THREAD

**Issue by Alice12133** [plusk01/adaptive-gyro-filtering#4]
1. 请问只更改plot绘图库是否能在windows10+vs2022环境下运行？
2. 请问在window10下cmake为什么最后build中没有adaptnotch.lib文件?是因为就算更改了plot绘图库也只能在支持POSIX的系统下运行吗

**Comment by plusk01** [comment]
You should be able to make it work for windows by altering the CMakeLists.txt. And probably dropping support for the terminal-based plotting. 

But I am not planning on adding windows support to this project.
